# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3ccda7ad7db4fa348ebdbfeabc0de1773d06e199d09f2f632f25335c845d361f69396c62cf1f00156fc31deded779701e287320c8e3976be6d577a85e68b46c

test:
  secret_key_base: 1b8fb2ffb3216f2759e042001df3b3312d826a80d3bf2a074de29bc9b94dc4cff19e9f2b1f4911ff8a2031b1a7811b7c477cc481121ee05784813048073293ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
